// cardData.js - Sample data for blog posts
export const cardData = [
  {
    id: 1,
    img: "https://picsum.photos/800/450?random=1",
    tag: "Engineering",
    title: "Revolutionizing software development with cutting-edge tools",
    description: "Our latest engineering tools are designed to streamline workflows and boost productivity across multiple development environments and frameworks...",
    authors: ["Remy Sharp", "Travis Howard"],
    date: "July 14, 2021",
  },
  {
    id: 2,
    img: "https://picsum.photos/800/450?random=2",
    tag: "Product",
    title: "Innovative product features that drive success",
    description: "Explore the key features of our latest product release that are helping businesses achieve their goals and exceed customer expectations...",
    authors: ["Erica Johns"],
    date: "July 12, 2021",
  },
  {
    id: 3,
    img: "https://picsum.photos/800/450?random=3",
    tag: "Design",
    title: "Designing for the future: trends and insights",
    description: "Stay ahead of the curve with the latest design trends and insights that shape modern user experiences...",
    authors: ["Kate Morrison"],
    date: "July 10, 2021",
  },
  {
    id: 4,
    img: "https://picsum.photos/800/450?random=4",
    tag: "Company",
    title: "Our company's journey: milestones and achievements",
    description: "Take a look at our company's journey and the milestones we've achieved in building innovative solutions...",
    authors: ["Cindy Baker"],
    date: "July 8, 2021",
  },
  {
    id: 5,
    img: "https://picsum.photos/800/450?random=45",
    tag: "Engineering",
    title: "Pioneering sustainable engineering solutions",
    description: "Learn about our commitment to sustainability and the innovative engineering solutions we're implementing...",
    authors: ["Agnes Walker", "Trevor Henderson"],
    date: "July 6, 2021",
  },
  {
    id: 6,
    img: "https://picsum.photos/800/450?random=6",
    tag: "Product",
    title: "Maximizing efficiency with our latest product updates",
    description: "Our recent product updates are designed to help you maximize efficiency and streamline your workflow processes...",
    authors: ["Travis Howard"],
    date: "July 4, 2021",
  },
];

export const latestArticles = [
  {
    id: 7,
    tag: "Engineering",
    title: "The future of AI in software engineering",
    description: "Artificial intelligence is revolutionizing software engineering by automating code generation, improving testing processes, and enhancing developer productivity across multiple frameworks and platforms...",
    authors: ["Remy Sharp", "Travis Howard"],
    date: "July 14, 2021",
  },
  {
    id: 8,
    tag: "Product",
    title: "Driving growth with user-centric product design",
    description: "Our user-centric product design approach is driving significant growth by focusing on customer needs, iterative feedback loops, and data-driven decision making that delivers exceptional user experiences...",
    authors: ["Erica Johns"],
    date: "July 12, 2021",
  },
  {
    id: 9,
    tag: "Design",
    title: "Modern UI/UX trends shaping digital experiences",
    description: "Explore the latest UI/UX design trends that are transforming digital experiences, from micro-interactions and dark mode preferences to accessibility-first design principles and mobile-native approaches...",
    authors: ["Kate Morrison", "Alex Chen"],
    date: "July 10, 2021",
  },
  {
    id: 10,
    tag: "Company",
    title: "Building a culture of innovation and collaboration",
    description: "Learn how we're fostering a workplace culture that encourages innovation, cross-team collaboration, and continuous learning to drive breakthrough solutions and employee satisfaction...",
    authors: ["Cindy Baker"],
    date: "July 8, 2021",
  },
  {
    id: 11,
    tag: "Engineering",
    title: "Scalable microservices architecture best practices",
    description: "Discover the essential best practices for building scalable microservices architectures that can handle high-traffic loads while maintaining system reliability and performance optimization...",
    authors: ["Agnes Walker", "Trevor Henderson"],
    date: "July 6, 2021",
  },
  {
    id: 12,
    tag: "Product",
    title: "Data-driven product development strategies",
    description: "Understanding how data analytics and user behavior insights are transforming product development strategies, enabling teams to make informed decisions and create products that truly resonate with users...",
    authors: ["Travis Howard", "Sarah Williams"],
    date: "July 4, 2021",
  },
  {
    id: 13,
    tag: "Design",
    title: "Accessibility in modern web design principles",
    description: "A comprehensive guide to implementing accessibility principles in modern web design, ensuring inclusive experiences for all users while maintaining visual appeal and functional excellence...",
    authors: ["Maya Patel"],
    date: "July 2, 2021",
  },
  {
    id: 14,
    tag: "Company",
    title: "Remote work strategies for distributed teams",
    description: "Effective strategies and tools for managing distributed teams in a remote-first world, including communication best practices, productivity tools, and maintaining company culture across time zones...",
    authors: ["Jordan Smith", "Lisa Rodriguez"],
    date: "June 30, 2021",
  },
  {
    id: 15,
    tag: "Engineering",
    title: "Cloud-native development and DevOps integration",
    description: "Exploring cloud-native development practices and seamless DevOps integration techniques that accelerate deployment cycles, improve system monitoring, and enhance overall application reliability...",
    authors: ["David Kim", "Rachel Thompson"],
    date: "June 28, 2021",
  },
];